### ISSUE TITLE
Apparently uses xf86-input-evdev, but forgets to install it

### ISSUE THREAD

**Issue by loawld432** [Justus0405/i3wm-dotfiles#1]
I did not have xf86-input-evdev installed, and i had to set nomodeset 3 as a kernel parameter to boot into tty and install xf86-input-evdev (sudo pacman -S xf86-input-evdev) so that I could use my mouse and keyboard. This also broke kde plasma so I couldnt even fix it outside of i3wm

**Comment by Justus0405** [comment]
Both the old and new installers automatically install xf86-input-evdev and xf86-input-synaptics. If these packages did not install correctly, you can switch to another TTY (use Ctrl + Alt + F2 for TTY2) and move the "40-libinput.conf" file from .config back to /usr/share/X11/xorg.conf.d/. After restarting, this should restore the default input settings.

I've already added a check to the new installer that exits the script immediately if the system can't update correctly, preventing potential system damage. However, I'm not sure what went wrong in your case.

**Comment by Justus0405** [comment]
I just tested the new installer on a virtual machine running KDE Plasma. The installation completed without any errors, and everything worked fine. Even after switching to xf86-input-evdev, mouse input in KDE continued to work flawlessly. Unfortunately, I'm unable to reproduce the issue you encountered.

**Comment by Tina-lel** [comment]
dumm

**Comment by Tina-lel** [comment]
DUUU-HUUUMm
