### ISSUE TITLE
how to change the wallpaper

### ISSUE THREAD

**Issue by GURUPRASATH-OG** [Justus0405/i3wm-dotfiles#2]
yo i tried adding feh  --bg-fill as a startup in i3 config instead of setting it to background it just opens the pic in feh. so help me out to change the wallpaper in you config

**Comment by Justus0405** [comment]
I use nitrogen instead of feh, just copy your wallpaper collection to ~/.config/wallpapers and open nitrogen using rofi, all your wallpapers should then be there, select the one you like and press apply at the bottom right corner, this should change your wallpaper and keep it along restarts

**Comment by GURUPRASATH-OG** [comment]
I figured it out bro after raising the issue only after some time i saw that nitrogen app then i found the to set wallpapers  and  i also added my wall folder in it. Sorry many i didnt look in to it before raising issue. As im usually manual guy so i only i cant figure it out.thanks for you info man your dot looks cool bro
